### ISSUE TITLE
Latest pyacvd 0.2.9 compilation from source fails when code is taken from PyPI

### ISSUE THREAD

**Issue by ashish-2022** [pyvista/pyacvd#27]
Latest pyacvd 0.2.9 compilation from source fails when code is taken from PyPI, https://files.pythonhosted.org/packages/d7/9d/1d10109cbd9409e0885d5a824ff2610d3adf2a2066a90abb66490ae9706a/pyacvd-0.2.9.tar.gz

Looks like this is fixed in main branch long time ago but PyPI source needs update.

```
D:\build_pyacvd\pyacvd-0.2.9>python -m pip install .
Processing d:\build_pyacvd\pyacvd-0.2.9
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      Traceback (most recent call last):
        File "C:\DE-Python\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 363, in <module>
          main()
        File "C:\DE-Python\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\DE-Python\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\ashish.shirodkar\AppData\Local\Temp\pip-build-env-ae4d0jag\overlay\Lib\site-packages\setuptools\build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\ashish.shirodkar\AppData\Local\Temp\pip-build-env-ae4d0jag\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "C:\Users\ashish.shirodkar\AppData\Local\Temp\pip-build-env-ae4d0jag\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 28, in <module>
        File "C:\Users\ashish.shirodkar\AppData\Local\Temp\pip-build-env-ae4d0jag\overlay\Lib\site-packages\Cython\Build\Dependencies.py", line 1010, in cythonize
          module_list, module_metadata = create_extension_list(
        File "C:\Users\ashish.shirodkar\AppData\Local\Temp\pip-build-env-ae4d0jag\overlay\Lib\site-packages\Cython\Build\Dependencies.py", line 845, in create_extension_list
          for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
        File "C:\Users\ashish.shirodkar\AppData\Local\Temp\pip-build-env-ae4d0jag\overlay\Lib\site-packages\Cython\Build\Dependencies.py", line 117, in nonempty
          raise ValueError(error_msg)
      ValueError: 'pyacvd/cython/_clustering.pyx' doesn't match any files
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by ashish-2022** [comment]
Hi @akaszynski,
pyacvd 0.2.7 is the last version which can be compiled using pip, 0.2.8 and 0.2.9 are failing.
I have checked compiling code code from main branch it works fine. Please upload new code on PyPI site.

**Comment by akaszynski** [comment]
Looks like 0.2.9 is missing some of the Cython files like `_clustering.pyx`. I'll fix that and create a PR.

**Comment by akaszynski** [comment]
@ashish-2022, just tagged v0.2.10. Release should complete by the end of today. Should it fail I'll debug and re-release.

**Comment by ashish-2022** [comment]
Thank you for your quick response @akaszynski .
