### ISSUE TITLE
ImportError: cannot import name '_clustering' from 'pyacvd'

### ISSUE THREAD

**Issue by TerenceCYJ** [pyvista/pyacvd#8]
Hi, there are some problem when I run this code.

Traceback (most recent call last):
  File "/home/cyj/project/others/pyacvd/example.py", line 2, in <module>
    import pyacvd
  File "/home/cyj/project/others/pyacvd/pyacvd/__init__.py", line 1, in <module>
    from pyacvd.clustering import Clustering
  File "/home/cyj/project/others/pyacvd/pyacvd/clustering.py", line 6, in <module>
    from pyacvd import _clustering
ImportError: cannot import name '_clustering' from 'pyacvd' (/home/cyj/project/others/pyacvd/pyacvd/__init__.py)

**Comment by tak0kada** [comment]
Have you tried ``python setup.py build_ext --inplace``?
